version: "3.12"

services:
  redis:
    image: redis
    ports:
      - 6379
  app:
    build:
      context: .
      target: development
    command: |
      sh entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
